sudo: required
services:
  - docker

before_install:
  - docker build -t ntan/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run ntan/react-test npm test -- --coverage
  
after_success:
  - docker build -t ntan/multi-client ./client
  - docker build -t ntan/multi-nginx ./nginx
  - docker build -t ntan/multi-server ./server
  - docker build -t ntan/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push ntan/multi-client
  - docker push ntan/multi-nginx
  - docker push ntan/multi-server
  - docker push ntan/multi-worker