sudo: required
services:
  - docker

before_install:
  - docker build -t robobooga/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run robobooga/react-test npm test -- --coverage
  
after_success:
  - docker build -t robobooga/multi-client ./client
  - docker build -t robobooga/multi-nginx ./nginx
  - docker build -t robobooga/multi-server ./server
  - docker build -t robobooga/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push robobooga/multi-client
  - docker push robobooga/multi-nginx
  - docker push robobooga/multi-server
  - docker push robobooga/multi-worker